name: PHPUnit - Woo Compatibility
on:
  # Manually for PoC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: ['nightly']
        php_versions: ['8.0']
    name: PHPUnit - WordPress ${{ matrix.wordpress_versions }} - PHP version ${{ matrix.php_versions }} - Woo Nightly
    env:
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          extensions: zip
      - name: Install Dependencies
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} ${{ matrix.wordpress_versions }} true
      - name: Run Woo Shortcode Tests
        env:
          TMPDIR: ${{ runner.temp }}
          LOAD_WOOCOMMERCE: yes
        run: |
          composer update --no-interaction
          ./vendor/bin/phpunit -v --debug tests/phpunit/elementor/woo
